// <auto-generated />
using LeadScraper.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeadScraper.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200516200956_WhoIs")]
    partial class WhoIs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("LeadScraper.Infrastructure.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BingKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlackListTerms")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhiteListTlds")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("LeadScraper.Infrastructure.Entities.WhoIsServer", b =>
                {
                    b.Property<string>("Tld")
                        .HasColumnType("TEXT");

                    b.Property<string>("Server")
                        .HasColumnType("TEXT");

                    b.HasKey("Tld");

                    b.ToTable("WhoIsServers");

                    b.HasData(
                        new
                        {
                            Tld = "com",
                            Server = "whois.verisign-grs.com"
                        },
                        new
                        {
                            Tld = "biz",
                            Server = "whois.biz"
                        },
                        new
                        {
                            Tld = "net",
                            Server = "whois.verisign-grs.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
